### ISSUE TITLE
Elección de un proyecto en SICOES

### ISSUE THREAD

**Issue by femandalorena** [Flecha-xD/flecha-xD#1]
Elegir un proyecto y mostrar para su aprobación desde las páginas de sicoes presentadas en la sesión de hoy

**Comment by femandalorena** [comment]
Elección del primer proyecto de Sicoes para el Instituto de la Juventud

**Comment by femandalorena** [comment]
Cambio del proyecto de Sicoes tras que hackearan el sitio web del proyecto original

**Comment by femandalorena** [comment]
Consulta sobre proyecto para el Ministerio de Comunicación y para el Ministerio de Justicia

**Comment by femandalorena** [comment]
Elección del proyecto CRM para el Ministerio de Justicia

**Comment by slaguna17** [comment]
Decision final, proyecto de ministerio de justicia
