### ISSUE TITLE
Hacer mockups

### ISSUE THREAD

**Issue by slaguna17** [Flecha-xD/flecha-xD#2]

**Comment by femandalorena** [comment]
Corrección del flujo de los mockups

**Comment by femandalorena** [comment]
Implementación de las funciones de "administrador de plataforma" o atencion al cliente dentro de configuraciones

**Comment by femandalorena** [comment]
Selección de colores de la aplicación por teoría del color (cambiable)

**Comment by slaguna17** [comment]
https://framer.com/share/xD--05MTcZfzOj3SwxWBiHTt#cwO7oWczW
presentacion de mockups
