### ISSUE TITLE
Inicializar servicios de google al codigo 

### ISSUE THREAD

**Issue by slaguna17** [Flecha-xD/flecha-xD#42]
Iniciar servicios de google dentro del codigo como un inicio a la implementacion de firebase

**Comment by femandalorena** [comment]
Implementación de archivos de google al codigo realizada

**Comment by femandalorena** [comment]
Complemento con las lineas entre archivos de gradle y dependencias

**Comment by femandalorena** [comment]
resultado exitoso, todo funcional
