### ISSUE TITLE
Redacción de la documentación

### ISSUE THREAD

**Issue by femandalorena** [Flecha-xD/flecha-xD#6]
Escritura analítica de los procesos seguidos en el proyecto para documentación .wiki

**Comment by femandalorena** [comment]
Investigación y Comparación con otros documentos de plataforma

**Comment by femandalorena** [comment]
Cambio de terminologías para incentivar la coherencia entre nombres, roles y procesos dentro de la aplicación

**Comment by slaguna17** [comment]
Debe estar terminada antes de iniciar la parte 2 del proyecto sin embargo solo falta arquitectura de software
