### ISSUE TITLE
Incorporar querys selectivos

### ISSUE THREAD

**Issue by femandalorena** [Flecha-xD/flecha-xD#66]
Realizar querys que seleccionen en la pantalla que mostrar segun lo requerido

**Comment by femandalorena** [comment]
Pantallas a realizar:
historial del usuario que seleccione reclamos por ci
historial de reclamos de funcionario: que seleccione reclamos por codigo de usuario

**Comment by slaguna17** [comment]
necesitamos mejorar el get que hacemos de firebase
