### ISSUE TITLE
ultimas correciones

### ISSUE THREAD

**Issue by slaguna17** [Flecha-xD/flecha-xD#72]
correciones de estilo de xml

**Comment by femandalorena** [comment]
agregar BS a recyclerview de subsidio
quitar checkbox de reclamo SI
toast para acceder---------------------
datos y nightmode guaardado cambiar toast
crear funcionario 
revisa rque el codigo no peuda sobreescribirse
modificarproducto subsidio arreglar xml 
modificar prodcuto activity no deja desoues de contraseña equivocada

**Comment by slaguna17** [comment]
ya esta crear funcionario (condicion)

**Comment by femandalorena** [comment]
agregar BS a recyclerview de subsidio, hecho no probado
quitar checkbox de reclamo, hecho no probado
datos y nightmode guaardado cambiar toast, hecho no probado
modificar producto subsidio arreglar xml, hecho no probado

**Comment by femandalorena** [comment]
probados, funcionales

**Comment by femandalorena** [comment]
probados, funcionales
