### ISSUE TITLE
Desarrollo de los casos de uso

### ISSUE THREAD

**Issue by femandalorena** [Flecha-xD/flecha-xD#9]
Creación de los diagramas con algún sooftware acordado

**Comment by femandamartinez** [comment]
![accederuser](https://user-images.githubusercontent.com/49009615/99396452-854a4100-28c0-11eb-9847-5452dc082eb8.png)
![configs](https://user-images.githubusercontent.com/49009615/99396459-867b6e00-28c0-11eb-91de-37f865621088.png)
![contacto](https://user-images.githubusercontent.com/49009615/99396461-867b6e00-28c0-11eb-8ba6-987178b0f742.png)
![normativa](https://user-images.githubusercontent.com/49009615/99396462-87140480-28c0-11eb-8fa2-69687681ae8e.png)
![reclamar](https://user-images.githubusercontent.com/49009615/99396463-87ac9b00-28c0-11eb-9529-70b16e1f0e56.png)
![subcidio](https://user-images.githubusercontent.com/49009615/99396464-87ac9b00-28c0-11eb-8a25-5e2fc677c408.png)

**Comment by femandalorena** [comment]
![admin](https://user-images.githubusercontent.com/49009615/99670011-a2147f00-2a4e-11eb-9415-6e99894577ac.png)
Desarrollo del Caso de Uso para el Administrador

**Comment by femandalorena** [comment]
Corrección de los casos de uso; cambio de nombre de administrador por atencion al cliente y del usuario por consumidor, de manera más especifica
